/**
 * The single source of truth for the palette.
 *
 * The design (`docs/design/*.dc.html`) hardcodes ~110 near-duplicate `oklch()` values inline.
 * They collapse into the roles below; every distinct value in the design maps onto one of
 * them. Dark is the design as-drawn. Light inverts lightness, holds chroma and hue, and
 * darkens the accents (see `docs/ARCHITECTURE.md#design-tokens`).
 *
 * `src/app/tokens.css` is generated from this file by `scripts/gen-tokens.ts`, and
 * `tokens.test.ts` fails if the two drift.
 */

export const tokens = {
  dark: {
    /* surfaces, from deepest chrome to most raised */
    'surface-chrome': 'oklch(0.13 0.012 285)',
    surface: 'oklch(0.17 0.012 285)',
    'surface-raised': 'oklch(0.21 0.014 285)',
    'surface-overlay': 'oklch(0.25 0.016 285)',
    'surface-hover': 'oklch(0.3 0.018 285)',
    'surface-accent': 'oklch(0.28 0.05 130)',

    /* lines */
    border: 'oklch(0.34 0.018 285)',
    'border-interactive': 'oklch(0.62 0.014 285)',

    /* ink */
    text: 'oklch(0.94 0.006 285)',
    'text-secondary': 'oklch(0.78 0.01 285)',
    'text-muted': 'oklch(0.68 0.012 285)',
    'on-accent': 'oklch(0.15 0.01 285)',

    /* accents */
    accent: 'oklch(0.82 0.16 130)',
    'accent-hover': 'oklch(0.86 0.16 130)',
    'accent-alt': 'oklch(0.72 0.14 290)',
    warn: 'oklch(0.78 0.12 60)',
    danger: 'oklch(0.7 0.13 25)',
    info: 'oklch(0.8 0.11 210)',
    focus: 'oklch(0.82 0.16 130)',
  },

  /**
   * Light is not the dark palette with the lights flipped. The design leans on luminous
   * accents against near-black; the same accents as large fills on white read garish. So in
   * light the accent is mostly ink and hairline, `--surface-accent` becomes a pale tint
   * rather than a saturated block, and the surface steps are compressed — separation comes
   * from borders and spacing instead of big lightness jumps.
   */
  light: {
    'surface-chrome': 'oklch(1 0 0)',
    surface: 'oklch(0.965 0.004 285)',
    'surface-raised': 'oklch(0.99 0.002 285)',
    'surface-overlay': 'oklch(0.97 0.005 285)',
    'surface-hover': 'oklch(0.955 0.006 285)',
    'surface-accent': 'oklch(0.96 0.04 130)',

    border: 'oklch(0.86 0.008 285)',
    'border-interactive': 'oklch(0.58 0.014 285)',

    text: 'oklch(0.22 0.014 285)',
    'text-secondary': 'oklch(0.38 0.016 285)',
    'text-muted': 'oklch(0.48 0.014 285)',
    'on-accent': 'oklch(0.99 0 0)',

    accent: 'oklch(0.52 0.15 130)',
    'accent-hover': 'oklch(0.45 0.14 130)',
    'accent-alt': 'oklch(0.5 0.18 290)',
    warn: 'oklch(0.52 0.13 60)',
    danger: 'oklch(0.55 0.19 25)',
    info: 'oklch(0.5 0.12 210)',
    focus: 'oklch(0.45 0.14 130)',
  },
} as const;

export type ThemeName = keyof typeof tokens;
export type TokenName = keyof (typeof tokens)['dark'];

const declarations = (theme: ThemeName, indent: string) =>
  Object.entries(tokens[theme])
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n');

/**
 * Light on `:root` so it is the no-JS, no-preference default; dark under both the media
 * query and the explicit attribute so system preference and the toggle each win where they
 * should. `:not([data-theme='light'])` is what lets an explicit light choice survive a dark
 * system preference.
 */
export function renderTokensCss(): string {
  return `/* Generated by scripts/gen-tokens.ts from src/lib/tokens.ts — do not edit. */

:root {
${declarations('light', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${declarations('dark', '    ')}
  }
}

[data-theme='dark'] {
${declarations('dark', '  ')}
}
`;
}
