/**
 * Placeholder content, verbatim from the design's SEED object. The bracketed values —
 * `[city]`, `[company]`, `[title], [author]` — are intentional: the owner replaces them.
 *
 * Post bodies are not here. They are authored as MDX in `src/content/posts/<slug>.mdx` and
 * loaded by `scripts/seed.ts` (D6), which is why every post carries `body: null` below.
 */
import { seedSchema } from '@/lib/content/schema';

export const seed = seedSchema.parse({
  about: {
    name: 'Qurat ul ain Fatima',
    role: 'senior software engineer',
    meta: '[city] · [timezone] · shipping since [year]',
    bio1: 'I like the problems that look boring from the outside and turn out to have a trapdoor in them. Schedulers. Cache invalidation. The third rewrite of a migration nobody asked for. I read the whole RFC, including the footnote that ruins your afternoon.',
    bio2: 'Currently at [company], where I work on [the thing]. Before that: [company], [company], and one startup that is now a cautionary tale I tell at parties.',
  },
  contact: {
    email: '[you]@[domain]',
    subject: 'a job / a bug / a bird photo',
    note: 'I reply to everything eventually. "Eventually" is doing a lot of work in that sentence.',
  },
  nowUpdated: '[date]',
  now: [
    { line: 'reading [book]' },
    { line: 'rewriting my [x] parser, 3rd time' },
    { line: 'learning [instrument], badly' },
    { line: 'open to staff roles' },
  ],
  projects: [
    {
      name: 'quietwatch',
      desc: 'a status page that only pings you when it actually matters',
      year: '2026',
      lang: 'go',
      tag: 'systems',
      draft: false,
      pinned: true,
    },
    {
      name: 'parsley',
      desc: 'a hand-written parser for a config format nobody asked for',
      year: '2026',
      lang: 'rust',
      tag: 'tools',
      draft: false,
      pinned: true,
    },
    {
      name: 'deadline',
      desc: 'turns your calendar into a burndown chart, ruthlessly',
      year: '2025',
      lang: 'ts',
      tag: 'tools',
      draft: false,
      pinned: true,
    },
    {
      name: 'cold start',
      desc: "a year of measuring one cloud's mood swings, in graphs",
      year: '2025',
      lang: 'py',
      tag: 'systems',
      draft: false,
      pinned: false,
    },
    {
      name: 'tabs.exe',
      desc: 'a tab manager shaped like a filing cabinet, killed by an API',
      year: '2024',
      lang: 'js',
      tag: 'silly',
      draft: false,
      pinned: false,
    },
    {
      name: 'grep for humans',
      desc: 'regexes explained by drawing them instead of shouting',
      year: '2024',
      lang: 'js',
      tag: 'tools',
      draft: false,
      pinned: false,
    },
    {
      name: 'retry budget',
      desc: 'a library that says no to your retry loop',
      year: '2024',
      lang: 'go',
      tag: 'systems',
      draft: false,
      pinned: false,
    },
    {
      name: 'logfold',
      desc: 'collapses 40k log lines into the six that matter',
      year: '2023',
      lang: 'rust',
      tag: 'tools',
      draft: false,
      pinned: false,
    },
    {
      name: 'queue depth',
      desc: 'a load generator that lies to you, but politely',
      year: '2023',
      lang: 'go',
      tag: 'systems',
      draft: false,
      pinned: false,
    },
    {
      name: 'birdcount',
      desc: 'counts the birds on my balcony, badly, with a camera',
      year: '2023',
      lang: 'py',
      tag: 'silly',
      draft: false,
      pinned: false,
    },
    {
      name: 'coffee ledger',
      desc: 'four years of espresso, logged, graphed, quietly regretted',
      year: '2022',
      lang: 'sql',
      tag: 'silly',
      draft: false,
      pinned: false,
    },
    {
      name: 'minipaxos',
      desc: 'consensus, 400 lines, purely so I would understand it',
      year: '2022',
      lang: 'rust',
      tag: 'systems',
      draft: true,
      pinned: false,
    },
  ],
  posts: [
    {
      slug: 'the-bug-was-in-the-calendar-obviously',
      title: 'The bug was in the calendar, obviously',
      blurb: 'Three days, one timezone, and a leap second that was never there.',
      date: 'Jul 2026',
      mins: '8 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'postgres-told-me-the-truth',
      title: "Postgres told me the truth, I just didn't listen",
      blurb: 'A query plan I ignored for six months, annotated line by line.',
      date: 'May 2026',
      mins: '12 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'a-cache-is-a-promise-to-your-future-self',
      title: 'A cache is a promise to your future self',
      blurb: 'And future you is not a reliable person.',
      date: 'Mar 2026',
      mins: '6 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'in-defence-of-the-extremely-boring-queue',
      title: 'In defence of the extremely boring queue',
      blurb: 'Every exciting queue I have met was exciting for bad reasons.',
      date: 'Jan 2026',
      mins: '9 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'how-i-read-a-codebase-i-am-afraid-of',
      title: 'How I read a codebase I am afraid of',
      blurb: 'Start at the deploy script. It cannot lie to you.',
      date: 'Nov 2025',
      mins: '14 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'nobody-wants-your-abstraction-yet',
      title: 'Nobody wants your abstraction yet',
      blurb: 'Three call sites is a pattern. Two is a coincidence.',
      date: 'Sep 2025',
      mins: '7 min',
      draft: false,
      pinned: false,
      body: null,
      canonical: null,
    },
    {
      slug: 'the-one-about-schedulers',
      title: 'The one about schedulers I keep not finishing',
      blurb: 'Half-written since March. Someday.',
      date: '—',
      mins: '?',
      draft: true,
      pinned: false,
      body: null,
      canonical: null,
    },
  ],
  talks: [
    {
      title: 'Everything I know about queues, in 25 minutes',
      venue: '[conference]',
      year: '2026',
      links: 'video ↗ slides ↗',
      draft: false,
      pinned: false,
    },
    {
      title: 'Migrations: a love story with three rollbacks',
      venue: '[conference]',
      year: '2025',
      links: 'video ↗',
      draft: false,
      pinned: false,
    },
    {
      title: 'You do not need a service mesh (probably)',
      venue: '[meetup]',
      year: '2024',
      links: 'slides ↗',
      draft: false,
      pinned: false,
    },
  ],
  shelf: [
    { title: '[title], [author]', state: 'now', note: 'p. 140 of 380' },
    { title: '[title], [author]', state: 'now', note: 'started [month]' },
    { title: '[title], [author]', state: 'done', note: 'best of the year so far' },
    { title: '[title], [author]', state: 'done', note: 're-read, held up' },
    { title: '[title], [author]', state: 'done', note: 'one chapter too long' },
    { title: '[title], [author]', state: 'soon', note: 'on the desk, guilt-shaped' },
    { title: '[title], [author]', state: 'soon', note: 'everyone keeps recommending it' },
    { title: '[title], [author]', state: 'gave up', note: "it wasn't you, it was chapter four" },
  ],
  uses: [
    { label: 'editor', value: '[editor], same config since [year]' },
    { label: 'shell', value: '[shell] and too many aliases' },
    { label: 'machine', value: '[laptop]' },
    { label: 'keyboard', value: '[keyboard], loud on purpose' },
    { label: 'notes', value: 'a plain text file, obviously' },
  ],
  cv: [
    {
      period: '[yr]–now',
      role: 'Senior Software Engineer, [company]',
      note: '[one line on what you own there]',
    },
    { period: '[yr]–[yr]', role: 'Software Engineer, [company]', note: '[one line]' },
    { period: '[yr]–[yr]', role: 'Software Engineer, [company]', note: '[one line]' },
    { period: '[yr]', role: '[degree], [university]', note: '' },
  ],
});
